In [ ]:
import tensorflow as tf
from tensorflow  import keras
from keras.datasets import mnist
from keras.layers import Dense,Flatten,Conv2D,AveragePooling2D
from keras.models import Sequential

In [ ]:
(x_train,y_train),(x_test,y_test) =mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train.shape[0]

60000

In [ ]:
#performing reshaping
x_train=x_train.reshape(x_train.shape[0],28,28,1)
x_test = x_test.reshape(x_test.shape[0],28,28,1)

In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
# Normalization
x_train =x_train /255
x_test =x_test/255   # min max 0-1


In [ ]:
y_train[0]

5

In [ ]:
#One hot Encoding
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test, 10)


In [ ]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
y_train[1]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
y_train[4]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
## Model Architecture
model=Sequential()
model.add(Conv2D(6,kernel_size =(5,5),padding='valid',activation='tanh',input_shape= (28,28,1)))
model.add(AveragePooling2D(pool_size= (2,2), strides = 2, padding = 'valid'))

model.add(Conv2D(16,kernel_size=(5,5),padding='valid',activation='tanh'))
model.add(AveragePooling2D(pool_size= (2,2), strides = 2, padding = 'valid'))

model.add(Flatten())
##ANN
model.add(Dense(120,activation='tanh'))
model.add(Dense(84,activation='tanh'))
model.add(Dense(10,activation='softmax'))




In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (AverageP  (None, 12, 12, 6)        0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 8, 8, 16)          2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 4, 4, 16)         0         
 ePooling2D)                                                     
                                                                 
 flatten (Flatten)           (None, 256)               0         
                                                                 
 dense (Dense)               (None, 120)               3

In [ ]:
model.compile(loss=keras.metrics.categorical_crossentropy , optimizer=keras.optimizers.Adam(),metrics=['accuracy'])


In [ ]:
model.fit(x_train, y_train, batch_size = 64, epochs=20 , verbose= 1, validation_data = (x_test, y_test))


Epoch 1/20
938/938 [==============================] - 15s 5ms/step - loss: 0.2868 - accuracy: 0.9146 - val_loss: 0.1290 - val_accuracy: 0.9620
Epoch 2/20
938/938 [==============================] - 5s 5ms/step - loss: 0.1021 - accuracy: 0.9695 - val_loss: 0.0811 - val_accuracy: 0.9737
Epoch 3/20
938/938 [==============================] - 5s 5ms/step - loss: 0.0686 - accuracy: 0.9785 - val_loss: 0.0619 - val_accuracy: 0.9790
Epoch 4/20
938/938 [==============================] - 4s 5ms/step - loss: 0.0550 - accuracy: 0.9826 - val_loss: 0.0556 - val_accuracy: 0.9818
Epoch 5/20
938/938 [==============================] - 5s 5ms/step - loss: 0.0433 - accuracy: 0.9860 - val_loss: 0.0548 - val_accuracy: 0.9834
Epoch 6/20
938/938 [==============================] - 4s 5ms/step - loss: 0.0371 - accuracy: 0.9881 - val_loss: 0.0496 - val_accuracy: 0.9831
Epoch 7/20
938/938 [==============================] - 4s 5ms/step - loss: 0.0296 - accuracy: 0.9910 - val_loss: 0.0548 - val_accuracy: 0.9824
Epoch

In [ ]:
score = model.evaluate(x_test, y_test)

print('Test loss:', score[0])
print('Test accuracy:', score[1])

313/313 [==============================] - 1s 3ms/step - loss: 0.0524 - accuracy: 0.9857
Test loss: 0.052443407475948334
Test accuracy: 0.9857000112533569


In [ ]:
predictions=model.predict(x_test)

313/313 [==============================] - 1s 2ms/step


In [ ]:
import numpy as np
imgpred=np.argmax(predictions[4])
imgpred

4